### ISSUE TITLE
Model needs a method for the round winner player

### ISSUE THREAD

**Issue by iron2414** [mykeesg/ELTE_Poker#15]
When the round ends i need to get the winner player, so i can send them to the clients and they can see who won.

**Comment by mykeesg** [comment]
The `getWinner()` method from the `AbstractPokerGame` class does exactly this.
https://github.com/mykeesg/ELTE_Poker/blob/master/PokerGame/src/main/java/model/AbstractPokerGame.java

**Comment by mykeesg** [comment]
The corresponding error got fixed in 0723cae
